name: "🐞 Bug Report"
description: Create a report related to a bug or another issue
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: ["xfox111"]

body:

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g. Sometimes when generating a password not all character sets are included
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. Generated password should include at least one character from every enabled character set
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction steps
      description: Precisely describe minimal number of steps that make the bug to appear
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See '...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, like screenshots, files, links, etc.
    validations:
      required: false

  - type: dropdown
    id: requested-help
    attributes:
      label: Are you willing to submit a PR for this issue?
      options:
        - "yes"
        - "no"
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: The provided reproduction is a minimal reproducible example of the bug.
          required: true
        - label: Check that the issue is still reproducable on the latest build image
          required: true
        - label: The entire issue was written in English.
          required: true
